### ISSUE TITLE
Разработка страницы авторизации (админ панель)

### ISSUE THREAD

**Issue by barashspb** [moevm/mse1h2024-telegram#14]
Страница авторизации является главной страницей бота, так как через неё авторизуется администратор для дальнейшей работ/настройки бота и раздачи доступа всем остальным пользователям
На данном этапе можно создать работающий прототип страницы без строгой привязки к созданным ранее UI макетам

**Comment by ImSOLty** [comment]
Задача декомпозирована: #15 и #19
