### ISSUE TITLE
Добавить Popup'ы

### ISSUE THREAD

**Issue by D1mitrii** [moevm/mse1h2024-telegram#142]
Необходим сделать **UI** более **User-Friendly** для этого нужно добавить [Popup'ы](https://guides.kontur.ru/components/popup-elements/toast/) (по ссылке пример). Они должны появляться после действия добавления/редактирования/удаления таблицы, преподавателей и т.д. **ВАЖНО:** Появляются только при получении ответа от сервера на данный запрос (**НЕ** должны появляться до ответа сервера).

**Comment by ImSOLty** [comment]
Задача не в приоритете. Won't fix.
