### ISSUE TITLE
Проверка кода в репозитории

### ISSUE THREAD

**Issue by barashspb** [moevm/mse1h2024-telegram#65]
Перед началом тестирования в Actions необходимо удостовериться, что весь необходимый код "залит" в main ветвь ИЛИ отдельные ветви отправлены в Pull Request

**Comment by ImSOLty** [comment]
Мало конкретики, большинство GHA воркфлоу уже реализованы, закрываю как Won't fix. При необходимости - переоткрывайте задачу
