### ISSUE TITLE
Исправление процесса авторизации

### ISSUE THREAD

**Issue by 1that** [moevm/mse1h2024-telegram#84]
Изменить вход через телеграмм на обычный ввод логина и пароля.

**Comment by ImSOLty** [comment]
[Протокол](https://github.com/moevm/mse1h2024-telegram/wiki/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D1%8B-%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87-%D1%81-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%87%D0%B8%D0%BA%D0%BE%D0%BC#%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B8-%D1%81-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%87%D0%B8%D0%BA%D0%BE%D0%BC-2---10424) созвона, в котором подробнее описана задача

**Comment by ImSOLty** [comment]
Соответствующие изменения должны быть внесены для backend

**Comment by ImSOLty** [comment]
UPD: вместо авторизации по "логину и паролю" достаточно использовать авторизацию "по паролю", т.к. администратор веб-приложения единственный. [Ссылка на обсуждение](https://discord.com/channels/1202516852065173516/1225406055526305862/1225456589188632656)
