### ISSUE TITLE
Поправить инструкцию по запуску

### ISSUE THREAD

**Issue by barashspb** [moevm/mse1h2024-telegram#85]
Внести все необходимые правки, чтобы инструкция по запуску бота стала максимально подробной и понятной

**Comment by ImSOLty** [comment]
Изменения, которые необходимо внести в инструкцию

1. Заменить раздел с авторизацией на новый вариант, указав на username и password переменные окружения (выполняется после исправления процесса авторизации). #84 
2. Вместо "Перейти на главную страницу" сослаться на инструкцию по использованию приложения (выполняется после написания инструкции по использованию) #88 
3. Исправить раздел с настройкой переменных окружения в соответствии с новой версией (выполняется после исправления процесса сборки) #86 
4. Указать альтернативные варианты настройки и запуска приложения:
	* вариант с использованием [localtunnel](https://github.com/localtunnel/localtunnel)
	* вариант с настройкой системы доменных имен

В остальном инструкция подробно описывает процесс настройки.

**Comment by ImSOLty** [comment]
Progress:

1. In progress...
2. In progress...
3. [Fixed](https://github.com/moevm/mse1h2024-telegram/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D1%83-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0#4-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D0%BE%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)
4. <Won't fix>

**Comment by ImSOLty** [comment]
Описанные выше изменения обработы, результаты представлены в [комментарии](https://github.com/moevm/mse1h2024-telegram/issues/85#issuecomment-2077035841)
