### ISSUE TITLE
Изменить docker-compose.yml (порты)

### ISSUE THREAD

**Issue by ImSOLty** [moevm/mse1h2024-telegram#87]
Необходимо исправить docker-compose.yml в соответствии с требованиями заказчика:

> Не мапьте порты хоста <1024  https://github.com/moevm/mse1h2024-telegram/blob/7a44db29d82c1d203249ea31621cc2e68dcc21a6/docker-compose.yml#L31

> Не выставляйте наружу порты СУБД https://github.com/moevm/mse1h2024-telegram/blob/7a44db29d82c1d203249ea31621cc2e68dcc21a6/docker-compose.yml#L57

**Comment by D1mitrii** [comment]
Стоит добавить Reverse-Proxy, которя будет единой точкой доступа в приложение (наружу будет только один порт)

**Comment by D1mitrii** [comment]
Решил пока что не добавлять Reverse-Proxy, так как могу что-то поломать под конец итерации. Предлагаю R-Proxy добавить позже.
